apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Dev Spaces
  - subscription.yaml
  # Node Feature Discovery
  - nfd-namespace.yaml
  - nfd-operatorgroup.yaml
  - nfd-subscription.yaml
  # NVIDIA GPU Operator
  - nvidia-namespace.yaml
  - nvidia-operatorgroup.yaml
  - nvidia-subscription.yaml
  # OpenShift AI
  - rhoai-namespace.yaml
  - rhoai-operatorgroup.yaml
  - rhoai-subscription.yaml
