apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Dev Spaces
  - checluster.yaml
  # Node Feature Discovery
  - nfd-instance.yaml
  # NVIDIA GPU
  - nvidia-clusterpolicy.yaml
  # OpenShift AI
  - rhoai-dsci.yaml
  - rhoai-dsc.yaml
